[dfmc-conversion] Improve runtime message for missing init keyword.
Prior to this change, the error looked like:

  Error: Missing init keyword specializer

After:

  Error: Missing init keyword "specializer:"

* sources/dfmc/conversion/define-class.dylan
  (compute-slot-initialization-code): Improve error text.